### ISSUE TITLE
[Feature request] Add overview and introductory remarks to documentation

### ISSUE THREAD

**Issue by thatfloflo** [lart-bangor/research-client#12]
**Describe the solution you'd like**
The documentation should have a short description of what the app is and why people might want to use, with some instruction on how to get started on the landing page. In addition there should be a more detailed documentation section giving background on the app/overview of features, etc. (preliminarily named "About") in docs/source.

**Comment by dakrismeno** [comment]
We've now settled on an agreed format of this. Wohoo
